### PR TITLE
Modify icon, escape quotes, json data

### PR DESCRIPTION
**Pull request by sstarcher**
Allow for the modification of the icon.
Escape quotes so the messages are not dropped.
Send data in json format.

### CODE REVIEW

**Comment by analytically** [comment]
Thanks for your contribution! Mind fixing the offences? https://travis-ci.org/sensu-plugins/sensu-plugins-slack/jobs/94770441

**Comment by sstarcher** [comment]
@analytically thanks and squashed

**Comment by analytically** [comment]
Thanks, mind adding an entry to the changelog?

**Comment by analytically** [comment]
Also, mind adding optional support for icon_emoji?

**Comment by sstarcher** [comment]
@brendangibat ^

**Pull request merged**
